from __future__ import annotations

from typing import Any

from fpdf import FPDF


class PDFReport(FPDF):
    def header(self) -> None:
        self.set_font("Helvetica", "B", 16)
        self.set_text_color(31, 119, 180)
        self.cell(0, 10, "AlphaGrid AI - Executive Brief", new_x="LMARGIN", new_y="NEXT", align="C")
        self.set_font("Helvetica", "I", 10)
        self.set_text_color(100, 100, 100)
        self.cell(
            0,
            6,
            "Guardrailed Time-Series Forecasting & Market-Intel Payload",
            new_x="LMARGIN",
            new_y="NEXT",
            align="C",
        )
        self.ln(4)
        self.set_draw_color(200, 200, 200)
        self.line(10, self.get_y(), 200, self.get_y())
        self.ln(6)

    def footer(self) -> None:
        self.set_y(-15)
        self.set_font("Helvetica", "I", 8)
        self.set_text_color(150, 150, 150)
        self.cell(0, 10, f"Page {self.page_no()} | Generated by AlphaGrid AI Platform", align="C")


def generate_executive_pdf(
    anomaly_event: dict[str, Any],
    thesis_data: dict[str, Any] | None,
    source_chunks: list[str] | None = None,
) -> bytes:
    """
    Generates an executive PDF report binary payload for downloading via Streamlit.
    """
    pdf = PDFReport()
    pdf.add_page()

    # Section 1: Anomaly Details
    pdf.set_font("Helvetica", "B", 12)
    pdf.set_text_color(0, 0, 0)
    pdf.cell(0, 8, "1. Flagged Grid Anomaly Event", new_x="LMARGIN", new_y="NEXT")

    pdf.set_font("Helvetica", "", 10)
    pdf.cell(50, 6, f"Grid Zone: {anomaly_event.get('market_symbol', 'DE_LU')}", new_x="RIGHT")
    pdf.cell(50, 6, f"Date: {anomaly_event.get('date', 'N/A')}", new_x="RIGHT")
    pdf.cell(
        50,
        6,
        f"Direction: {anomaly_event.get('direction', 'N/A')}",
        new_x="LMARGIN",
        new_y="NEXT",
    )

    pdf.cell(50, 6, f"Magnitude: {anomaly_event.get('magnitude', 0):,.0f} MW", new_x="RIGHT")
    pdf.cell(50, 6, f"Z-Score: {anomaly_event.get('zscore', 0):.2f}", new_x="LMARGIN", new_y="NEXT")
    pdf.ln(6)

    # Section 2: Thesis Payload
    if thesis_data:
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "2. Validated Market Trading Thesis", new_x="LMARGIN", new_y="NEXT")

        pdf.set_font("Helvetica", "", 10)
        pos = thesis_data.get("position_direction", "N/A")
        horizon = thesis_data.get("target_horizon_hours", 24)
        pdf.cell(60, 6, f"Position Direction: {pos}", new_x="RIGHT")
        pdf.cell(60, 6, f"Target Horizon: {horizon} Hours", new_x="LMARGIN", new_y="NEXT")
        pdf.ln(4)

        pdf.set_font("Helvetica", "B", 10)
        pdf.cell(0, 6, "Market Reasoning:", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 9)
        pdf.multi_cell(0, 5, thesis_data.get("reasoning", "N/A"))
        pdf.ln(4)

        citations = thesis_data.get("verbatim_citations", [])
        if citations:
            pdf.set_font("Helvetica", "B", 10)
            pdf.cell(0, 6, "Verbatim Citations (Verified):", new_x="LMARGIN", new_y="NEXT")
            pdf.set_font("Helvetica", "I", 9)
            for cit in citations:
                pdf.multi_cell(0, 5, f'- "{cit}"')
                pdf.ln(2)

    # Section 3: Source Chunks
    if source_chunks:
        pdf.ln(4)
        pdf.set_font("Helvetica", "B", 12)
        pdf.cell(0, 8, "3. Vector Store Source Context (ChromaDB)", new_x="LMARGIN", new_y="NEXT")
        pdf.set_font("Helvetica", "", 8)
        for idx, chunk in enumerate(source_chunks):
            pdf.multi_cell(0, 4, f"Chunk {idx + 1}: {chunk}")
            pdf.ln(2)

    return bytes(pdf.output())
